# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-25 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awardapp', '0005_rates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='Followers',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='Following',
        ),
        migrations.AddField(
            model_name='profile',
            name='contact',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
